### ISSUE TITLE
Repository moved

### ISSUE THREAD

**Issue by wdm0006** [conda-forge/category_encoders-feedstock#2]
This repo has moved from my personal github into scikit-learn-contrib: https://github.com/scikit-learn-contrib/categorical-encoding, so I would image something needs to change here to keep it up to date.

**Comment by bollwyvl** [comment]
Great, sounds like a good home for it!

I saw we're still back a version, so have updated to the newest over on #3.

Also, on the new repo, I've proposed [adding the LICENSE.md](https://github.com/scikit-learn-contrib/categorical-encoding/pull/15) to the package, so that we can specify it more formally here with `license_file`.

**Comment by bollwyvl** [comment]
Ok, looks like #3 was successful, and everything is [up on anaconda.org](
https://anaconda.org/conda-forge/category_encoders/files?version=1.2.3). 

Huzzah!
